[package]
name = "disket"
version = "0.1.0"
license = "MIT"
authors = ["Marcos Brito <marcos.brito0507@gmail.com>"]
description = ""
repository = "https://github.com/marcos-brito/disket"
readme = "README.md"
rust-version = "1.75"
keywords = ["device", "disk", "volume"]
edition = "2021"

[features]
default = ["device", "watch", "mount"]
device = []
watch = []
mount = ["windows/Win32_Storage_FileSystem"]
os = []

[dependencies]

[target.'cfg(windows)'.dependencies]
windows = { version = "0.61.1", optional = true }
