on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
      name: Build for ${{ matrix.target }}
      runs-on: ${{ matrix.os || "ubuntu-latest" }}
      strategy:
        matrix:
          # Running tests with cross is unreliable on some platforms. If
          # you get any weird errors change `test` to false.
          include:
            - target: x86_64-pc-windows-gnu
              test: true
            - target: x86_64-unknown-linux-gnu
              test: true
            - target: x86_64-unknown-freebsd
              test: true
            - target: aarch64-linux-android              
              test: true
            - target: aarch64-apple-ios
              os: macos-latest
              test: true
            - target: x86_64-apple-darwin
              os: macos-latest
              test: true

      steps:
        - uses: actions/checkout@v4
        
        - name: Install Rust target
          run: rustup target add ${{ matrix.target }}

        - name: Install cross
          uses: taiki-e/install-action@v2
          with:
            tool: cross@0.2.5

        - name: Test
          run: cross test --all-features --all-targets --target ${{ matrix.target }}
          if: ${{ matrix.test }}

        - name: Build
          run: cross build --release --all-features --all-targets --target ${{ matrix.target }}

  docs:
      name: Check docs for ${{ matrix.target }}
      runs-on: ubuntu-latest
      strategy:
        matrix:
          target:
            - x86_64-unknown-linux-gnu
            - x86_64-unknown-freebsd
            - x86_64-apple-darwin
            - x86_64-pc-windows-msvc
            - aarch64-linux-android
            - aarch64-apple-ios
      steps:
        - uses: actions/checkout@v4

        - name: Install Rust target
          run: rustup target add ${{ matrix.target }}

        - name: Check docs
          run : cargo doc --all-features --no-deps --target ${{ matrix.target }}
