on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  test:
      name: Test for ${{ matrix.os }}
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          # There isn't a FreeBSD machine
          os: 
            - ubuntu-latest
            - windows-latest
            - macos-latest

      steps:
        - uses: actions/checkout@v4
        
        - name: Test library
          run: cargo test  --all-features --all-targets 

  build:
      name: Build for ${{ matrix.target }}
      runs-on: ubuntu-latest
      strategy:
        matrix:
          target:
            - x86_64-unknown-linux-gnu
            - x86_64-unknown-freebsd
            - x86_64-apple-darwin
            - x86_64-pc-windows-msvc
            - aarch64-linux-android
            - aarch64-apple-ios
      steps:
        - uses: actions/checkout@v4
        
        - name: Install Rust target
          run: rustup target add ${{ matrix.target }}
        
        - name: Build library
          run: cargo build --release --all-features --all-targets --target ${{ matrix.target }}

  docs:
      name: Check docs for ${{ matrix.target }}
      runs-on: ubuntu-latest
      strategy:
        matrix:
          target:
            - x86_64-unknown-linux-gnu
            - x86_64-unknown-freebsd
            - x86_64-apple-darwin
            - x86_64-pc-windows-msvc
            - aarch64-linux-android
            - aarch64-apple-ios
      steps:
        - uses: actions/checkout@v4

        - name: Check docs
          run : cargo doc --all-features --no-deps --target ${{ matrix.target }}
