on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
      name: Build for ${{ matrix.platform.target }}
      runs-on: $ {{ matrix.platform.os }}
      strategy:
        matrix:
          platform:
            - os: windows-latest
              target: x86_64-pc-windows-msvc
              cross: false
            - os: macos-latest
              target: x86_64-apple-darwin
              cross: false
            - os: ubuntu-latest
              target: x86_64-unknown-linux-gnu
              cross: false
            - os: ubuntu-latest
              target: x86_64-unknown-freebsd
              cross: true
            - os: ubuntu-latest
              target: aarch64-linux-android              
              cross: true
            - os: macos-latest
              target: aarch64-apple-ios
              cross: true
      steps:
        - uses: actions/checkout@v4
        
        - name: Install Rust target
          run: rustup target add ${{ matrix.target }}

        - name: Install cross
          run: cargo install cross --git https://github.com/cross-rs/cross --branch main

        - name: Test with cargo
          run: cross test --all-features --all-targets --target ${{ matrix.platform.target }}
          if: ${{ !matrix.platform.cross }}

        - name: Test with cross
          run: cargo test --all-features --all-targets --target ${{ matrix.platform.target }}
          if: ${{ !matrix.platform.cross }}

        - name: Build with cargo
          run: cross build --release --all-features --all-targets --target ${{ matrix.platform.target }}
          if: ${{ !matrix.platform.cross }}

        - name: Build with cross
          run: cargo build --release --all-features --all-targets --target ${{ matrix.platform.target }}
          if: ${{ matrix.platform.cross }}

  docs:
      name: Check docs for ${{ matrix.target }}
      runs-on: ubuntu-latest
      strategy:
        matrix:
          target:
            - x86_64-unknown-linux-gnu
            - x86_64-unknown-freebsd
            - x86_64-apple-darwin
            - x86_64-pc-windows-msvc
            - aarch64-linux-android
            - aarch64-apple-ios
      steps:
        - uses: actions/checkout@v4

        - name: Install Rust target
          run: rustup target add ${{ matrix.target }}

        - name: Check docs
          run : cargo doc --all-features --no-deps --target ${{ matrix.target }}
